---

- name: Install NPM packages
  shell: "npm install --quiet --silent"
  args:
    chdir: "{{ deploy_dir }}"
  tags:
    - install
  when: ( do_install is defined and do_install|bool == true ) or
        ( do_update is defined and do_update|bool == true )

- name: Update packages based on package.json
  shell: "npm upgrade --quiet --silent"
  args:
    chdir: "{{ deploy_dir }}"
  tags:
    - upgrade
  when: ( do_install is defined and do_install|bool == true ) or
        ( do_update is defined and do_update|bool == true )

- name: Update global packages to their latest version.
  become: true
  shell: "npm upgrade --quiet --silent --global"
  args:
    chdir: "{{ deploy_dir }}"
  tags:
    - upgrade
  when: ( do_install is defined and do_install|bool == true ) or
        ( do_update is defined and do_update|bool == true )

- name: Restart the server.
  become: false
  shell: "npm run restart"
  args:
    chdir: "{{ deploy_dir }}"
  tags:
    - restart
  when: ( do_restart is defined and do_restart|bool == true )
