---

- name: Install NPM packages
  shell: "npm install --quiet --silent"
  args:
    chdir: "{{ deploy_dir }}"
  tags: ['install', 'packages']

- name: Update packages based on package.json
  shell: "npm upgrade --quiet --silent"
  args:
    chdir: "{{ deploy_dir }}"
  tags: ['install', 'upgrade', 'packages']

- name: Update global packages to their latest version.
  become: true
  shell: "npm upgrade --quiet --silent --global"
  args:
    chdir: "{{ deploy_dir }}"
  tags: ['install', 'upgrade', 'packages']

#- name: Restart the server
#  become: false
#  shell: "npm run restart"
#  args:
#    chdir: "{{ deploy_dir }}"
#  tags: ['install', 'upgrade', 'reboot']

- name: npm stop
  shell: "npm stop"
  args:
    chdir: "{{ deploy_dir }}"
  ignore_errors: true
  tags: ['install', 'upgrade', 'restart', 'deploy']

- name: restart server
  shell: "npm start"
  args:
    chdir: "{{ deploy_dir }}"
  tags: ['install', 'upgrade', 'restart', 'deploy']



